### ISSUE TITLE
[proposal] Add cosmosAddress Property in verificationMethod like a ethereumAddress

### ISSUE THREAD

**Issue by daoauth** [decentralized-identity/did-resolver#103]
[[proposal] jwt validation using cosmosAddress #204](https://github.com/decentralized-identity/did-jwt/issues/204)

Since Cosmos uses prefixes for addresses, it is an advantageous address system to use as did. So, after decomposing the address into prefix and remainder, we want to use it as a DID. And, like Ethereum, Cosmos would like to add the address of Cosmos to the property so that it can be verified by extracting the public key from the signature.

dsrv1zp78zmtj4a7qvs4p2s08ngjn9rcwpaf5k9d0la (cosmos address)
did:dsrv:1zp78zmtj4a7qvs4p2s08ngjn9rcwpaf5k9d0la (did)

```javascript
interface VerificationMethod {
  id: string
  type: string
  controller: string
  publicKeyBase58?: string
  publicKeyBase64?: string
  publicKeyJwk?: JsonWebKey
  publicKeyHex?: string
  publicKeyMultibase?: string
  blockchainAccountId?: string
  ethereumAddress?: string
  cosmosAddress?: string
}
```

**Comment by peacekeeper** [comment]
I would recommend to also add it to the W3C DID Spec Registries:

https://w3c.github.io/did-spec-registries/#verification-method-properties

**Comment by daoauth** [comment]
Updated to https://github.com/OR13/lds-blockchain2021/pull/3 for further clarification.

**Comment by daoauth** [comment]
https://github.com/w3c/did-spec-registries/issues/347
