### ISSUE TITLE
Exporting the JsonWebKey interface

### ISSUE THREAD

**Issue by bshambaugh** [decentralized-identity/did-resolver#125]
Is there any reason why the JsonWebKey interface is not exported? I know it was used internally. but could it be?

https://github.com/decentralized-identity/did-resolver/blob/master/src/resolver.ts#L74-L86

**Comment by mirceanis** [comment]
There's no specific reason other than wanting to minimise the exported API, to reduce the maintenance burden.
Besides this, the `JsonWebKey` defined here intentionally only refers to the public parts of a JWK, to discourage the use and leaking of private keys in DID documents.

We can close this after merging your PR #126
