### ISSUE TITLE
further parameter for resolving

### ISSUE THREAD

**Issue by froid1911** [decentralized-identity/did-resolver#19]
Hello everone,

I'd would like to see that i could add further parameter to the resolve function.
e.g. didResolver.resolve(did, {some: "extra", stuff }

What do you think?
I could create a pull request for that.

kind regards,
Frank

**Comment by mirceanis** [comment]
What would be the use-case?

**Comment by froid1911** [comment]
3Box 3id-resolver relies on 0.0.6 where provide a parameter whether the result should be pinned to the IPFS node or not.
https://github.com/3box/3id-resolver/blob/master/src/register.js#L24

**Comment by mirceanis** [comment]
While there may be use-cases like this to require extra parameters for DID resolution, this is still a base layer for a very large number of applications that rely on it being straight-forward.
The expectation is that there is a direct and unique correspondence between `DID` -> `DID doc`
Adding a parameter here opens up the possibility of resolving the same DID to different documents based on various parameters. I know this is not your use-case but it would make it possible.

Also, the 3id resolver you pointed to seems to be using an outdated version of this library, with a different method signature for `resolve(...)`.

**Comment by simonas-notcat** [comment]
I agree with @mirceanis . What you probably could do is write a wrapper function, that handles these extra parameters. Something like:

```js

const customResolve = (did) => resolve(did, {pin: true})

const resolver = new Resolver({
  custom: customResolve
  ...ethrResolver,
  ...webResolver,
})
```

**Comment by froid1911** [comment]
thanks @simonas-notcat I will look into your solution. <3
