### ISSUE TITLE
Did resolver should not require a did to be hex encoded

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/did-resolver#3]
I'm building a Universal DID resolver, and I want to use this lib, but I cannot because it [enforces that all dids should be hex encoded]( https://github.com/uport-project/did-resolver/blob/develop/src/resolver.ts#L76), which is the case for all uport's did methods, but is not necessarily the case in general.

I suggest to move this check to each individual did method's `resolve` function

**Comment by pelle** [comment]
@gjgd We don't enforce that they are hex encoded. We had missed an underscore in the regex.

**Comment by ajunge** [comment]
@pelle @mi-xu is this fixed already?
