### ISSUE TITLE
Add support for didResolutionMetadata and didDocumentMetadata

### ISSUE THREAD

**Issue by oed** [decentralized-identity/did-resolver#79]
According to [did-core](https://w3c.github.io/did-core/#did-resolution) a resolver function should have the following abstract form:
```
resolve(did, resolutionOptions) →
   « didResolutionMetadata, didDocument, didDocumentMetadata »
```

Currently the function signature for this library looks like this:
```ts
resolve(did: string): Promise<DIDDocument>
```

We should introduce a breaking change that adds support for returning *didResolutionMetadata* and *didDocumentMetadata*.
It should be possible to implement this in a way in which all resolvers won't break with the new version of this package, but won't provide additional metadata until they implement the new interface. 

The new function signature would look something like this:
```ts
interface ResolutionResult {
  didDocument: DIDDocument
  didResolutionMetadata: DIDResolutionMetadata
  didDocumentMetadata: DIDDocumentMetadata
}

resolve(did: string, resolutionOptions: ResolutionOptions): Promise<ResolutionResult>
```

**Comment by mirceanis** [comment]
Yes, thank you for flagging this!
Do you plan to contribute a PR to fix this?

**Comment by oed** [comment]
I'm planning to do that yes! :)

**Comment by oed** [comment]
To reduce complexity, ensure spec compliance and code readability, I will likely make this a breaking change without backwards compatibility. This means that all method specific resolvers would need to be changed in order to support the new version.

**Comment by mirceanis** [comment]
A breaking change is unfortunate, but if it is indeed necessary it should not be a show-stopper.
I look forward to your PR :)
