### ISSUE TITLE
How to build this project with an example?

### ISSUE THREAD

**Issue by adityaishan** [decentralized-identity/did-resolver#8]
It would be great if it can have instructions on how to build and run the project with an example.

**Comment by mirceanis** [comment]
I'm not sure what you mean.

This repo holds the source of the `did-resolver` library.
It is being built using standard npm scripts and distributed on [the standard package registry](https://www.npmjs.com/package/did-resolver)

If you want to do a local build, you can run something like:
```
> npm install
> npm pack
```

Closing this; please reopen if this does not answer your question.
